version: '2.1'

services:
  redis:
    image: redis
    container_name: redis-instance-1
    expose:
      - 6379
  node-redis-proxy:
    image: node-redis-proxy
    container_name: node-redis-proxy
    build: .
    environment:
      BACKING_REDIS_ADDRESS: redis-instance-1
      BACKING_REDIS_PORT: 6379
    expose:
      - 8080
  tests:
    image: node-redis-proxy-tests
    build: ./e2e/
    environment:
      BACKING_REDIS_ADDRESS: redis-instance-1
      BACKING_REDIS_PORT: 6379
      HOST: node-redis-proxy
      PORT: 8080
